### PR TITLE
Invalid version in prod builds

### LINKED ISSUE #173: Raven reports invalid version for PROD builds
Looks like Electron [checks `package.json`](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetversion) for version information. When we deploy a release, there's no package.json. Perhaps `electron` embeds version information another way?

Worst comes to worst, we can embed `package.json`? I wouldn't like to, though

### PR DESCRIPTION
**Pull request by tomitm**
Specify `app-version` property in `electron-packager` so that `app.getVersion()` returns the correct version.
Cleanup: constants, require/imports in electron-app.js
Fixes #173.

### CODE REVIEW

**Comment by tomitm** [comment]
Verified working on Windows, haven't checked Linux and OSX builds yet.

**Comment by mitchhentges** [comment]
:+1:

**Comment by mitchhentges** [comment]
Jk, no :+1: here.
[`electron-prebuilt` doesn't set a version for Linux](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#app-version), so Linux still reports Electron's version, not James'.

We should still set `app-version`, that's a good idea. Perhaps we should `envify` a version, as well?

**Comment by tomitm** [comment]
Should be ready to go now, thanks for checking that!

Shame about `app.getVersion()`. Wonder if electron-packager (or electron) would consider that a bug.. although, considering the following, might be misconfiguration on our part:

> [**app.getVersion()**](https://github.com/electron/electron/blob/969a30fc3bf12dd4b5bad5e193e43a340a45ac8b/docs/api/app.md#appgetversion)
> Returns the version of the loaded application. If no version is found in the application's `package.json file`, the version of the current bundle or executable is returned.

Checks `package.json` first, and looking at `binaries\James-linux-x64\resources\app\package.json`, ours is:

```json
{
  "main": "./electron-app.js"
}
```

Going to see if I can figure out why that's happening, then maybe I can revert back to `app.getVersion()`.

**Comment by tomitm** [comment]
Ah, that didn't take long to find... [this `package.json`](https://github.com/james-proxy/james/blob/master/resource/package.json) is why.

This package.json gets packaged up, and of course, it doesn't have a `version` value, so electron falls back to the executable's `appVersion`.

**Comment by tomitm** [comment]
Alright, removed the `resources/package.json` file and setup gulp to copy in `./package.json` so it gets packaged properly. That should be the proper fix!

**Comment by mitchhentges** [comment]
This breaks `npm start`, because `main` no longer links to the `build` folder.
This can be solved, by changing the `start` script to: `cd build && electron . && cd ..`, but if `electron` fails to start, then it'll leave the user in the `build` folder.

**Comment by mitchhentges** [comment]
Confirmed to work in Linux, Mac, and (VM) Windows. Nice.

**Comment by tomitm** [comment]
Yeah, hold on, I'll have to figure out a better solution for `package.json`. Think I might need to generate it during gulp.

Going to dig around and see how much of `package.json` gets used by electron, as so far, it sounds like the `main` and `version` fields are important, but what else? Haven't found clear docs yet.

Also, this part isn't true, at least on Windows:

> but if electron fails to start, then it'll leave the user in the build folder.

**Comment by mitchhentges** [comment]
No, that leaving in the build folder would only occur of you used my "cd
and electron and cd  .." fix

**Comment by tomitm** [comment]
Should be good now. :sparkles:

**Comment by mitchhentges** [comment]
Version is correctly shown for Windows, Mac, and Linux. `npm run build && npm start`, `npm run development` and `npm run package` work nicely for all platforms, too. Nice work

**Pull request merged**
